### ISSUE TITLE
Restrictions being invalidated by terms of GPL

### ISSUE THREAD

**Issue by v1993** [pali/libopenaptx#12]
*Disclaimer, just in case: I'm not affiliated with Freedesktop and Collabora in any way*

Your readme says (emphasis mine):

> This library and any other project which uses this library must not be used in
> other organizations, projects, applications, libraries (and in any other
> software form) incompatible with libopenaptx licence or where current license of
> this project is violated or where previous version of this library/license was
> violated. ***Freedesktop and Collabora are examples of such projects which are not
> allowed to use this library in any form due to license violations.***

GPL3 appears to forbid this. Quoting section 7 (see for list of applicable additions):

> All other non-permissive additional terms are considered “further restrictions” within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

Your terms appear to impose restrictions that can be waived under terms of GPL license, thus making them inapplicable. If you're sure that your license terms are being violated you should take legal action, either by yourself or with help of some open-source organization that provide legal help.

If you wish to enforce such restriction no matter what you should switch to another license that doesn't invalidate your additional restrictions.

P.S.: please correct me if I'm wrong in my understanding terms of GPL. I'm not a lawyer myself.

**Comment by pali** [comment]
There is no additional restriction, library is under GPLv3 and therefore is fully compatible with GPLv3 projects. GPLv3 does not allow violation of license and these sections are just explicit description that projects which violate license cannot use this project.

**Comment by CounterPillow** [comment]
pali is correct in that if a license violation has occurred, the GPLv3 states that the community surrounding the project has to reinstate the license, and it will not be automatically reinstated. Therefore, "Freedesktop and Collabora are examples of such projects which are not allowed to use this library in any form due to license violations." is a completely valid statement to make for a GPLv3 project.

However, the question is whether there was a license violation, and why one would care this much about one, but it's not my code so not my place to make claims about it.

**Comment by v1993** [comment]
Alright, I see what you mean: those should not be taken as *additional* restrictions, just as highlighting the actual GPL terms. Thanks for clearing this up!

**Comment by ZanderBrown** [comment]
> just as highlighting the actual GPL terms

However it was previously LGPL

**Comment by Lunarequest** [comment]
I'd like to point out that while you can ban freedesktop from contributing to this project. Banning them from using it isn't actually possible without violating
GPL. 

Similarly it was not a license violation to ban you from contributing to freedesktop projects since they didn't restrict you from using and getting the source code of their projects. If you do wish to prevent freedesktop from using this project you should consider using a EULA and moving to source available over open source.

**Comment by pali** [comment]
@advaithm: This is not about banning but about license violation. I have already put information into README file and also explained it. There is no EULA, no restrictions and project is fully under GPLv3. And those who violates license can be restricted from its usage as GPL does not allow license violation. Exact rules are defined in §8/GPLv3.

**Comment by ZanderBrown** [comment]
Interestingly the README doesn't comment on `LGPL-2.1-or-later` → `GPL-3.0-or-later` which whilst probably legally okay is still ethically interesting and has potentially major implications for users

**Comment by Lunarequest** [comment]
FYI freedesktop uses libopenaptx in pipewire (source: [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/meson.build#L31)). I believe based on what I have read they didn't violate LGPL since they used code you sent in the pr was licensed under LGPL this also reflected in the pr which used your work in [pulseaudio](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/440). While you can request they remove your code you can't legally enforce this.

**Comment by pali** [comment]
> I believe based on what I have read they didn't violate LGPL since they used code you sent in the pr was licensed under LGPL this also reflected in the pr which used your work in pulseaudio.

Stop believing them. This is not truth. They violate license. See: https://github.com/pali/libopenaptx/issues/13

**Comment by Lunarequest** [comment]
> > I believe based on what I have read they didn't violate LGPL since they used code you sent in the pr was licensed under LGPL this also reflected in the pr which used your work in pulseaudio.
> 
> Stop believing them. This is not truth. They violate license. See: #13

They no longer user libopenaptx, they have moved to libfreeaptx.

**Comment by Lunarequest** [comment]
> > I believe based on what I have read they didn't violate LGPL since they used code you sent in the pr was licensed under LGPL this also reflected in the pr which used your work in pulseaudio.
> 
> Stop believing them. This is not truth. They violate license. See: #13

also fyi they did try and reach out to you many times after you were banned but you blocked their emails.

**Comment by pali** [comment]
This is another lie. I was who tried to contact them many times last year and nobody replied back.

**Comment by Lunarequest** [comment]
@pali there have been people who have "taken back" opensource code in the past and the answer from the fsf has always been you can but you can't force others not to use it. Your code in pulseaudio stems from your past contributions and have properly been assigned to you. 

For more information on the take back opensource code stuff this is a pretty good breakdown https://www.zdnet.com/article/no-you-cant-take-open-source-code-back/
